name: Build APK Only

on:
  workflow_dispatch: # 方便你手动点击运行

jobs:
  build:
    runs-on: ubuntu-latest # 改用 Linux，速度更快更稳定
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # 关键步骤：下载作者需要的特殊 android.jar
      - name: Download android.jar
        run: |
          mkdir -p $ANDROID_HOME/platforms/android-34
          curl -L https://raw.githubusercontent.com/Reginer/aosp-android-jar/refs/heads/main/android-34/android.jar -o $ANDROID_HOME/platforms/android-34/android.jar

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Android APK
        run: ./gradlew assembleDebug

      # 将生成的 APK 传到 GitHub 界面供下载
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Nrfr-Latest-APK
          path: app/build/outputs/apk/debug/*.apk
